apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Namespace }}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
data:
  SERVICE: {{ .Chart.Name }}
  VERSION: {{ .Chart.Version }}
  KAFKA_HOST: kafka-cp-kafka.kafka:9092
  KAFKA_CONNECT_HOST: kafka-cp-kafka-connect.kafka:8083
  ROUTING: http://{{ .Release.Namespace }}-routing-service-car:5000
  MINIO_BUCKET: {{ .Chart.Name }}
  MINIO_ENDPOINT: minio.minio:9000
  SCHEMA_REGISTRY_HOST: http://{{ .Release.Namespace }}-kafka-cp-schema-registry:8081

